name: CI
on: [push]
jobs:
  test:
    permissions:
      id-token: 'write'
      contents: 'read'
    steps:
      - name: Fetching secrets from conjur
        uses: cyberark/conjur-action@v2.0.2
        with:
          url: ${{ secrets.CONJUR_URL }}
          account: DEMO
          authn_id: ${{ secrets.CONJUR_AUTHN_ID }}
          secrets: test/host1/user|TEST_USER;test/host1/pass|TEST_PASS
      - name: Checking the result
        run: |
          echo Show env detail:
          cat env | grep TEST
          echo "$TEST_USER:$TEST_PASS" | base64
